#!/usr/bin/env python
from datetime import datetime
from dateutil import parser
import os, sys

valid = sys.argv[1]
print valid
date = os.popen('echo "Valid from: Sun Jan 24 07:20:13 PST 2016 until: Wed Feb 22 07:20:13 PST 2017"')
string = date.read()
string = string.split("until: ")[-1:]
expiration_date = parser.parse(string[0])
print (expiration_date - datetime.today()).days
